[server.pv.error]
version_not_supported = "Lo sentimos, tu versión de Plasmo Voice no es compatible con este servidor. %s"
player_only_command = "&cSolo jugadores pueden ejecutar este comando"
mod_missing_kick_message = "Lo sentimos, necesitas instalar el mod Plasmo Voice para jugar en este servidor.\nDescárgalo aquí: https://modrinth.com/plugin/plasmo-voice"
player_not_found = "Jugador no encontrado"
version_not_supported_click = "Descargar versión compatible"
no_permissions = "&cLo siento, pero no tienes permiso para ejecutar este comando. Por favor, ponte en contacto con un administrador si crees que esto es un error."
version_not_supported_hover = "%s"
[server.pv.mutes]
empty_reason = "Sin especificar"
permanently_muted = "Has sido silenciado de forma permanente. Motivo: %s"
temporarily_muted = "Has sido silenciado %1$s. Motivo: %2$s"
unmuted = "Ya no estás silenciado"

[server.pv.mutes.durations]
days = "durante %s d"
seconds = "durante %s seg"
hours = "durante %s h"
weeks = "durante %s sem"
minutes = "durante %s min"
[server.pv.command.mute_list]
entry_muted_by = "%1$s fue silenciado por %2$s, expira: %3$s. Motivo: %4$s"
entry = "%1$s, expira: %2$s. Motivo: %3$s"
never_expires = "Nunca"
expiration_time = "HH:mm:ss"
header = "Jugadores silenciados:"
expire_at = "%1$s en %2$s"
expiration_date = "dd/MM/yyyy"
empty = "No hay jugadores silenciados"
[server.pv.command.reconnect]
message = "Paquete de reconexión enviado."
[server.pv.command.reload]
message = "Configuración Recargada."
[server.pv.command.mute]
permanently_muted = "%1$s ha sido silenciado permanentemente. Motivo: %2$s"
temporarily_muted = "%1$s ha sido silenciado %2$s. Motivo: %3$s"
already_muted = "%s ya se encuentra silenciado."
usage = "Uso correcto: /vmute <player> [duration] [reason]"
[server.pv.command.unmute]
usage = "Uso correcto: /vunmute <player>"
unmuted = "%s ya no está silenciado."
not_muted = "%s no se encuentra silenciado."
[server.pv.command.list]
message = "Clientes (%1$s/%2$s): %3$s"
empty = "No hay jugadores con Plasmo Voice instalado."
[client.pv.activation]
proximity = "Proximidad"
