
[Rendering]
	#Changes Zephyr and Aerwhale rendering to use their old models from the b1.7.3 version of the mod
	"Switches to legacy mob models" = false
	#Disables the Aether's custom skybox in case you have a shader that is incompatible with custom skyboxes
	"Disables Aether custom skybox" = false

[Gui]
	#Changes the vanilla Minecraft menu into the Aether menu
	"Enables Aether menu" = false
	#Adds a button to the top right of the main menu screen to toggle between the Aether and vanilla menu
	"Enables Aether menu button" = false
	#Changes the background panorama into a preview of the latest played world
	"Enables world preview" = false
	#Adds a button to the top right of the main menu screen to toggle between the panorama and world preview
	"Enables toggle world button" = false
	#Adds a button to the top right of the main menu screen to allow quick loading into a world if the world preview is enabled
	"Enables quick load button" = false
	#Determines that menu elements will align left if the menu's world preview is active, if true, this overrides 'Align menu elements left'
	"Align menu elements left with world preview" = false
	#Aligns the elements of the vanilla menu to the left, only works if 'Align menu left with world preview' is set to false
	"Align vanilla menu elements left" = false
	#Aligns the elements of the Aether menu to the left, only works if 'Align menu left with world preview' is set to false
	"Align Aether menu elements left" = true
	#Adds random trivia and tips to the bottom of loading screens
	"Enables random trivia" = false
	#Makes the extra hearts given by life shards display as silver colored
	"Enables silver life shard hearts" = true

[Audio]
	#Sets the minimum delay for the Aether's music manager to use if needing to reset the song delay outside the Aether
	"Set backup minimum music delay" = 12000
	#Sets the maximum delay for the Aether's music manager to use if needing to reset the song delay outside the Aether
	"Set backup maximum music delay" = 24000
	#Disables the Aether's internal music manager, if true, this overrides all other audio configs
	"Disables Aether music manager" = false
	#Disables the Aether's menu music in case another mod implements its own, only works if 'Disables Aether music manager' is false
	"Disables Aether menu music" = false
	#Disables the menu music on the vanilla world preview menu, only works if 'Disables Aether music manager' is false
	"Disables vanilla world preview menu music" = false
	#Disables the menu music on the Aether world preview menu, only works if 'Disables Aether music manager' is false
	"Disables Aether world preview menu music" = false

