debug = false
disable_crowdin = false
check_for_updates = true

key_bindings = []



[voice]
disabled = false
microphone_disabled = false
activation_threshold = -30.0
input_device = ""
output_device = ""
use_javax_input = false
microphone_volume = 1.0
noise_suppression = false
volume = 1.0
compressor_limiter = true
sound_occlusion = false
directional_sources = false
hrtf = false
stereo_capture = false


[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

