debug = false
disable_crowdin = false
check_for_updates = true

[[key_bindings]]
name = "key.plasmovoice.general.mute_microphone"
any_context = false
category = "key.plasmovoice.general"

[[key_bindings.keys]]
code = 90
type = "KEYSYM"

[servers.c5a40bf3-6696-4033-b529-249049b4c984.distances]
4aec07ba-d109-3345-9a0a-92022a116cd0 = 32

[addons.pv-addon-soundphysics]
"gui.plasmovoice.soundphysics.mic_reverb_volume" = 1.0
"gui.plasmovoice.soundphysics.enabled" = true
"gui.plasmovoice.soundphysics.mic_reverb" = true

[voice]
disabled = false
microphone_disabled = true
activation_threshold = -30.0
input_device = "OpenAL Soft on VoiceMeeter Aux Output (VB-Audio VoiceMeeter AUX VAIO)"
output_device = ""
disable_input_device = false
use_javax_input = false
microphone_volume = 1.0
noise_suppression = false
volume = 1.0
compressor_limiter = true
sound_occlusion = true
directional_sources = true
hrtf = true
stereo_capture = false

[voice.volumes.source_04abdaf0-1c8a-3ea3-a696-21415185a924]
volume = 1.5
[voice.volumes.proximity]
volume = 1.0
[voice.volumes.source_3d7f8ddb-b6b9-47dd-bb5b-44e62a2dffce]
volume = 1.0
[voice.volumes.source_7a86ca0f-3e7b-3fb2-bb16-57c5f023ae5e]
volume = 1.0

[advanced]
visualize_voice_distance = true
visualize_voice_distance_on_join = false
compressor_threshold = -10
limiter_threshold = -6
directional_sources_angle = 145
stereo_sources_to_mono = false
panning = true
camera_sound_listener = true
exponential_volume_slider = true
exponential_distance_gain = true

[overlay]
show_activation_icon = true
activation_icon_position = "BOTTOM_CENTER"
show_source_icons = 0
show_static_source_icons = true
overlay_enabled = true
overlay_position = "TOP_LEFT"
overlay_style = "NAME_SKIN"

[overlay.source_states]
proximity = "ON"
